name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type (patch, minor, major)"
        required: true
        default: "patch"

jobs:
  bump_version:
    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Release
        run: npm run release -- ${{ github.event.inputs.release_type }}

      - name: Get version
        id: get_version
        run: echo "::set-output name=VERSION::$(jq -r .version package.json)"

      - name: Switch Branch
        run: git checkout -b release_${{ steps.get_version.outputs.VERSION }}

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release_${{ steps.get_version.outputs.VERSION }}

  lint:
    runs-on: ubuntu-latest
    needs: bump_version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: release_${{ needs.bump_version.outputs.VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: bump_version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: release_${{ needs.bump_version.outputs.VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm run test

  release:
    runs-on: ubuntu-latest

    needs:
      - bump_version
      - lint
      - test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "npm"

      - name: Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Git Pull
        run: git pull --ff-only origin release_${{ needs.bump_version.outputs.VERSION }}

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Package
        run: npm run package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.bump_version.outputs.VERSION }}
          release_name: Release ${{ needs.bump_version.outputs.VERSION }}
          draft: true
          prerelease: false

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            a11y-visualizer-chrome.zip
            a11y-visualizer-firefox.zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./a11y-visualizer-chrome.zip
          asset_name: a11y-visualizer-chrome.zip
          asset_content_type: application/zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./a11y-visualizer-firefox.zip
          asset_name: a11y-visualizer-firefox.zip
          asset_content_type: application/zip
